name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hallo World"
      - name: Print Goodbye
        run: echo "Goodbye"
      
